/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input button1,
    input button2,
    input button3,
    input button4,
    input button5,
    input button6,
    input button7,
    input button8,
    input button9,
    input button10,
    input button11,
    input button12,
    input button13,
    input button14,
    input button15,
    input button16
  );
  
  
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  reg rst;
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = {button1, button2, button3, button4, button5, button6, button7, button8};
  end
endmodule
